[ADD]22기 iltal backend 모델링 완성
wecode-bootcamp-korea/22-2nd-iltal-backend pull request #1
Opened 2021-07-20 07:01 UTC by Jacesoul

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 모델링 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- create users
- create products
- create books
- create core

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-20 09:59 UTC, lordmyshepherd requested changes
마이너한 리뷰 몇개 남겼습니다~ 확인해주세요~

2021-07-20 09:59 UTC, lordmyshepherd commented on products/models.py
> +    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='categories')
related_name `sub_categories`로 만들어야 하지 않나요?

```suggestion
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='categories')
```

2021-07-20 09:59 UTC, lordmyshepherd commented on products/models.py
> +    subcategory    = models.ForeignKey('Subcategory', on_delete=models.CASCADE, related_name='subcategories')
마찬가지로, related_name `products`로 만들어야 하지 않나요?

2021-07-20 09:59 UTC, lordmyshepherd commented on products/models.py
> +    coordinate     = models.JSONField()
👍

2021-07-20 09:59 UTC, lordmyshepherd commented on products/models.py
> +    price          = models.IntegerField()
decimal field 사용하지 않아도 되나요?

2021-07-20 10:11 UTC, Jacesoul commented on products/models.py
> +    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='categories')
넵! 변경했습니다~~

2021-07-20 10:11 UTC, Jacesoul commented on products/models.py
> +    subcategory    = models.ForeignKey('Subcategory', on_delete=models.CASCADE, related_name='subcategories')
넵! 변경했습니다~~

2021-07-20 10:11 UTC, Jacesoul commented on products/models.py
> +    price          = models.IntegerField()
넵! 변경했습니다~~

2021-07-20 10:11 UTC, Jacesoul commented on products/models.py
> +    coordinate     = models.JSONField()
:pray::pray:

2021-07-21 01:22 UTC, lordmyshepherd commented
LGTM 👍 👍

2021-07-21 01:22 UTC, merged