[iltal backend jihoon] kakao social login 구현
wecode-bootcamp-korea/22-2nd-iltal-backend pull request #10
Opened 2021-07-26 11:22 UTC by wlgns410

- create kakao-signin
- create test.py

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

<img width="566" alt="스크린샷 2021-07-26 오후 8 14 17" src="https://user-images.githubusercontent.com/81137234/126980779-3f1ce145-7d9b-4e3d-a424-e441a7c1a114.png">

<img width="734" alt="스크린샷 2021-07-26 오후 8 20 46" src="https://user-images.githubusercontent.com/81137234/126980864-9da42eb7-ecdd-4646-b5ca-e1ad936c2d2e.png">

2021-07-27 02:17 UTC, lordmyshepherd requested changes
마이너한 리뷰 2개만 반영해주세요~

2021-07-27 02:17 UTC, lordmyshepherd commented on users/views.py
> +            access_token     = request.headers.get('Authorization')
```suggestion
            kakao_access_token     = request.headers.get('Authorization')
```

2021-07-27 02:17 UTC, lordmyshepherd commented on users/views.py
> +            user_info        = requests.get('https://kapi.kakao.com/v2/user/me', headers=headers).json()
`info`라는 말을 붙이는 습관은 좋지 않습니다~

```suggestion
            kakao_user        = requests.get('https://kapi.kakao.com/v2/user/me', headers=headers).json()                
```

2021-07-27 02:17 UTC, lordmyshepherd commented on users/views.py
> +            access_token = jwt.encode({'user_id': user.id}, SECRET_KEY, ALGORITHM)
나머지는 코드가 너무 깔끔하네요~

2021-07-27 04:11 UTC, wlgns410 commented on users/views.py
> +            access_token = jwt.encode({'user_id': user.id}, SECRET_KEY, ALGORITHM)
넵 감사합니다.

2021-07-27 04:11 UTC, wlgns410 commented on users/views.py
> +            user_info        = requests.get('https://kapi.kakao.com/v2/user/me', headers=headers).json()
넵 수정했습니다.

2021-07-27 04:11 UTC, wlgns410 commented on users/views.py
> +            access_token     = request.headers.get('Authorization')
넵 수정했습니다.

2021-07-27 04:12 UTC, wlgns410 commented
<img width="385" alt="스크린샷 2021-07-27 오후 1 12 24" src="https://user-images.githubusercontent.com/81137234/127094192-ddf38ea2-90e5-4c58-b71f-2f7b2d93f100.png">

2021-07-27 07:01 UTC, wlgns410 commented
리베이스 완료했습니다.

2021-07-28 00:48 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-07-28 00:49 UTC, merged