[iltal backend JIWOO] 제품 전체보기 및 상세보기 Products 앱 완성
wecode-bootcamp-korea/22-2nd-iltal-backend pull request #3
Opened 2021-07-21 07:36 UTC by Jacesoul

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 제품 전체보기 및 상세보기 Products 앱 완성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- ADD filter for category, subcategory, region, group, price
- ADD pagenation function(offset, limit)
- CREATE urls.py

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-21 07:37 UTC, Jacesoul commented
![스크린샷 2021-07-21 오후 4 37 24](https://user-images.githubusercontent.com/75877363/126450146-718e70a2-3b7c-41ad-a36b-32baaefdd782.png)
![스크린샷 2021-07-21 오후 4 37 37](https://user-images.githubusercontent.com/75877363/126450180-878711dc-6e5d-4e47-aa5c-b259de7d9a20.png)

2021-07-21 08:06 UTC, lordmyshepherd requested changes

2021-07-21 08:06 UTC, lordmyshepherd commented on products/views.py
> +class ProductView(View):
List를 반환하는 경우에는 `ProductsView` 혹은 `ProductListView`로 변수명을 정하는게 Django View 네이밍 컨벤션입니다~
```suggestion
class ProductsView(View): 
```

2021-07-21 08:06 UTC, lordmyshepherd commented on products/views.py
> +            price       = request.GET.get('price',None)
`request.GET.get(, None)`의 경우에는 default로 `None`을 반환하게 되는데 아래 필터링 할때 문제 안생기나요?

` q_object &= Q(subcategory__category=None)` 괜찮은 건가요?

```suggestion
            category    = request.GET.get('category',None)
            subcategory = request.GET.get('subcategory',None)
            region      = request.GET.get('region',None)
            group       = request.GET.get('group',None)
            price       = request.GET.get('price',None)
```

2021-07-21 08:06 UTC, lordmyshepherd commented on products/views.py
> +            total_product_count = Product.objects.all().count()
`total_count`도 반환해주는 경우라면, filtering된 상품의 개수만 반환해주도록 만들어주셔야 합니다!
그래야 상품 리스트를 조회한 client에서 명확하게 조회된 상품의 개수만 알 수 있습니다.

2021-07-21 08:06 UTC, lordmyshepherd commented on products/views.py
> +            }for product in products]
```suggestion
            } for product in products]
```

2021-07-21 08:06 UTC, lordmyshepherd commented on products/views.py
> +                products = Product.objects.select_related('subcategory').filter(q_object).order_by(price)[offset:limit]
이렇게 구현하면 price가 존재하는 경우에 두번 쿼리(DB hit 2번)를 해야되지 않나요?
line 35와 line 39를 합쳐볼 수 있지 않을까요?

2021-07-21 08:06 UTC, lordmyshepherd commented on products/views.py
> +                products = Product.objects.select_related('subcategory').filter(q_object).order_by(price)[offset:limit]
`select_related`로 subcategory를 join해서 가져오고 있는데, 아래에서 사용하지 않는 것 같아요. Django query loggin하는 방법을 찾아보시고, 쿼리를 최적화 해보시면 어떨까요?

```suggestion
                products = Product.objects.select_related('subcategory').filter(q_object).order_by(price)[offset:limit]
```

2021-07-21 08:21 UTC, Jacesoul commented on products/views.py
> +class ProductView(View):
ProductListView로 수정했습니다~!

2021-07-21 08:22 UTC, Jacesoul commented on products/views.py
> +            price       = request.GET.get('price',None)
if category: 로 None값을 걸려주었기 때문에 괜찮은것 같습니다!

2021-07-21 08:24 UTC, Jacesoul commented on products/views.py
> +            total_product_count = Product.objects.all().count()
여기서 total_product_count는 페이지네이션을 위해 프런트에서 전체 상품의 갯수를 알수 있게 전달을 해주는데 혹시 filtering된 상품의 개수만 반환해야하는 이유가 있을까요?

2021-07-21 08:25 UTC, Jacesoul commented on products/views.py
> +            }for product in products]
변경했습니다~!

2021-07-21 08:54 UTC, lordmyshepherd commented on products/views.py
> +            total_product_count = Product.objects.all().count()
`offset` `limit`으로 페이지네이션 구현하는데 전체 상품의 개수가 어떤 상황에서 필요한가요???
데이터 구조가 어색해요.

2021-07-21 09:06 UTC, Jacesoul commented on products/views.py
> +                products = Product.objects.select_related('subcategory').filter(q_object).order_by(price)[offset:limit]
if price: 
                products = Product.objects.select_related('subcategory').filter(q_object).order_by(price)[offset:limit]
            else:
                products = Product.objects.select_related('subcategory').filter(q_object)[offset:limit]
이렇게 변경하면 DB에 한번만 hit하지 않을까요?

2021-07-21 09:07 UTC, Jacesoul commented on products/views.py
> +                products = Product.objects.select_related('subcategory').filter(q_object).order_by(price)[offset:limit]
select *
  from products
 inner join subcategories
    on products.subcategory_id = subcategories.id
 where subcategories.category_id = (select id from categories where id = 1);

Django query loggin 해보니까 이렇게 나오는것을 확인했습니다. 
여기서 더욱 최적화 해보려 했지만 쉽지 않네요 ㅜㅜㅜ

2021-07-21 10:22 UTC, lordmyshepherd requested changes

2021-07-21 10:22 UTC, lordmyshepherd commented on products/views.py
> +                products = Product.objects.select_related('subcategory').filter(q_object).order_by(price)[offset:limit]
`:8000/products?ordering=-price` 또는 `:8000/products?ordering=price`와 같은 URI가 되도록 구현해 주셔야 URI만 보고도 의미를 명확하게 파악할 수 있습니다.

그리고 아래와 같이 코드를 수정하면 `if`, `else`는 사용하지 않아도 될 것 같아요!

```python
ordering = request.GET.get('ordering', id) 

q = Q()

if category:
    q &= Q(subcategory__category=category)

products = Product.objects.select_related('subcategory').filter(q_object).order_by(ordering)[offset:limit]

```

2021-07-21 10:22 UTC, lordmyshepherd commented on products/views.py
> +                products = Product.objects.select_related('subcategory').filter(q_object).order_by(price)[offset:limit]
위에 쿼리는 더이상 최적화 할게 없습니다! 아래 코드에서 for문이 실행될때 많은 쿼리가 발생한다는 얘기였습니다.

```python
results = [{
                'id'      : product.id,
                'title'   : product.title,
                'price'   : product.price,
                'bgimg'   : product.background_url,
                'userImg' : product.host.profile_url,
                'name'    : product.host.user.name,
                'nick'    : product.host.nickname
            } for product in products]
```

그래서 결론적으로 왜 `select_related('subcategory')`를 하시는지 궁굼합니다.

2021-07-21 10:24 UTC, lordmyshepherd requested changes

2021-07-21 10:24 UTC, lordmyshepherd commented on products/views.py
> +            total_product_count = Product.objects.all().count()
프론트에서 필터링되지 않은 전체 상품에 개수를 알아야되는 이유가 이해가 잘 안됩니다.
`offset`, `limit`으로 필요한 양만큼 호출하고 만약에 더이상 상품이 없으면 빈 리스트를 반환하도록 구현해주셔야 합니다.

2021-07-22 00:40 UTC, Jacesoul commented on products/views.py
> +            total_product_count = Product.objects.all().count()
생각해보니 전체상품의 개수는 불필요한것 같습니다!

2021-07-22 00:47 UTC, Jacesoul commented on products/views.py
> +                products = Product.objects.select_related('subcategory').filter(q_object).order_by(price)[offset:limit]
오호! 너무 좋은방법이네요! default값으로 랜덤한 값으르 주고 싶어서 물음표(?)를 적용해보았습니다!

2021-07-22 00:49 UTC, Jacesoul commented on products/views.py
> +                products = Product.objects.select_related('subcategory').filter(q_object).order_by(price)[offset:limit]
제가 select_related를 제대로 이해하지 못하고 적용한것 같습니다 ㅜㅜ 
다시 공부한 뒤에 'subcategory'를 'host','host__user'로 변경해 보았습니다. 
results값에서는 product의 host와 host에 연결된 user만 가지고 오더라구요!

2021-07-22 01:26 UTC, lordmyshepherd requested changes

2021-07-22 01:26 UTC, lordmyshepherd commented on products/views.py
> +            } for product in products]
한칸 띄워주세요!

2021-07-22 01:26 UTC, lordmyshepherd commented on products/views.py
> +                q_object &= Q(is_group=group)
If문 로직과 queryset 로직 사이에 한 칸 띄워주세요~

2021-07-22 01:26 UTC, lordmyshepherd commented on products/views.py
> +            products = Product.objects.select_related('host','host__user').filter(q_object).order_by(ordering)[offset:limit]
👍

2021-07-22 01:26 UTC, lordmyshepherd commented on products/views.py
> +            return JsonResponse({"message":results},status=200)
마찬가지로 한 칸 띄워주세요!

2021-07-22 01:26 UTC, lordmyshepherd commented on products/views.py
> +            results = [{
get() 메소드 호출시 매칭되는 레코드(데이터)가 없는 경우에 대한 에러 핸들링이 안되어 있는 것 같아요!

2021-07-22 01:26 UTC, lordmyshepherd commented on users/models.py
> +    user        = models.ForeignKey(User, on_delete=models.CASCADE)
`Unique` 설정 없이 `OneToOneField`를 사용하는게 어떨까요?

2021-07-22 01:32 UTC, lordmyshepherd requested changes

2021-07-22 01:32 UTC, lordmyshepherd commented on products/views.py
> +            offset      = offset * limit
Offset에 limit을 곱하는 이유가 있을까요?

2021-07-22 01:49 UTC, Jacesoul commented on products/views.py
> +            } for product in products]
넵!

2021-07-22 01:49 UTC, Jacesoul commented on products/views.py
> +                q_object &= Q(is_group=group)
넵!

2021-07-22 01:50 UTC, Jacesoul commented on products/views.py
> +            products = Product.objects.select_related('host','host__user').filter(q_object).order_by(ordering)[offset:limit]
:pray:

2021-07-22 01:50 UTC, Jacesoul commented on products/views.py
> +            return JsonResponse({"message":results},status=200)
넵!

2021-07-22 01:57 UTC, Jacesoul commented on users/models.py
> +    user        = models.ForeignKey(User, on_delete=models.CASCADE)
OneToOneField로 변경해보았습니다.

2021-07-22 03:07 UTC, Jacesoul commented on products/views.py
> +            offset      = offset * limit
1,2,3,4 .. 페이지가 있을경우 첫페이지에서 다음페이지로 넘어갈때  product 슬라이싱에서 2번째 페이지에서 상품 개수의 시작을 알리기위해 곱셈을 사용했습니다. 
ex) 
한페이지에 12개의 상품을 넣어 놓고 2번째 페이지에 갈 경우 ,
프런트에서 offset값을 1로 주게 되면 limit의 기본값은 12가 되고 
처음 시작의 offset은 1*12 =12 로 되어 두번째 페이지의 상품시작은 pk=12부터 시작합니다. 

혹시 다른 방법으로 구현할수 있을까요?

2021-07-22 03:07 UTC, Jacesoul commented on users/models.py
> +    user        = models.ForeignKey(User, on_delete=models.CASCADE)
**feature/modeling 에서 수정요청 했습니다.

2021-07-22 04:00 UTC, Jacesoul commented on products/views.py
> +            total_product_count = Product.objects.all().count()
말씀하신부분 적용해서 전체상품 개수를 삭제했습니다!

2021-07-22 04:00 UTC, Jacesoul commented on products/views.py
> +            results = [{
except Product.DoesNotExist:
            return JsonResponse({"message":"INVAILD_PRODUCT"},status=400)
DoesNotExist코드 추가했습니다~!

2021-07-23 06:37 UTC, lordmyshepherd commented on products/views.py
> +                products = Product.objects.select_related('subcategory').filter(q_object).order_by(price)[offset:limit]
👍 이제 제대로 잘 적용하신 것 같습니다! 4시에 공유되는 Django ORM 최적화 세션영상 보시면서 다시 개념 잡아보시면 좋을 것 같아요!

2021-07-23 06:40 UTC, lordmyshepherd commented on products/views.py
> +            offset      = offset * limit
1, 2, 3 페이지 기준으로 만드시면 안되고 offset, limit으로 들어오는 값으로만 반환해준다고 생각하셔야 해요 ㅎㅎ

```python
offset = 0&limit=10으로 들어오면,
offset = 0, limit = offset + limit으로만 리턴해주면 됩니다.

offset = 10&limit=10으로 들어오면,
offset = 10, limit = 10 + 10으로만 리턴해주면 됩니다.
```

2021-07-23 06:40 UTC, lordmyshepherd commented
컨플릭트 해결해주시고, 유닛테스트 추가해주세요~

2021-07-25 07:06 UTC, Jacesoul commented on products/views.py
> +            offset      = offset * limit
프런트에서 offset과 limit 모두 들어온다고 생각해야겠군요!

2021-07-26 02:03 UTC, lordmyshepherd requested changes

2021-07-26 02:03 UTC, lordmyshepherd commented on products/views.py
> +
3줄 지워주세요~ class와 class 사이에는 한 칸만 띄워주세요~

2021-07-26 02:03 UTC, lordmyshepherd commented on core/views.py
> +                # request.user = User.objects.get(id=1)
if, else를 나눈 이유가 있으신가요?

로그인한 회원과 비회원의 경우에 대응할 수 있도록 만드신 것 같은 느낌이 나네요??
Public(인증 필요 없는) 엔드포인트와 Private(인증 필수) 엔드포인트는 데코레이터로 분리하는 방법보다는 엔드포인트 자체를 나누는 방법이 관리하기에 깔끔합니다. 아래와 같은 방법으로요~

```python
/api/private/products
/api/public/products

```

2021-07-26 02:03 UTC, lordmyshepherd commented on products/tests.py
> +class ProductsTest(TestCase):
테스트 코드 깔끔하게 잘 작성하신 것 같습니다!! 👍 

참고) 나중에는 테스트 코드도 성능과 속도를 고려해야 하는 시기가 오게됩니다. 이때는 아래와 같은 고민을 해보시면 도움이 많이 될 것 같습니다. 지금 당장은 적용하지 않으셔도 됩니다~

**setUp()**
`TestCase`를 상속받은 경우, `setUp()`은 각각의 `test_method`가 실행될 때마다 실행됩니다. 
그렇기 때문에 테스트 중에 내용이 변경될 수 있는 객체를 생성할 수 있습니다.
ex)
```python
    def setUp(self):
        user = User.objects.create(name="a")

    def test_xxxx(self):
        user.name = "b"
        user.save()
        ....
```
이런 경우가 아니라면, 즉 test 전체에서 사용되는 수정되거나 변경되지 않을 객체들을 생성하는 경우에 `setUp`에서 객체를 생성하게 되면 매번 객체를 생성하게 되므로 느려집니다.

**setUpTestData()**
테스트에서 읽기 전용 데이터로만 사용하는 객체의 경우 class method인 `setUpTestData`를 사용하면 한번만 생성할 수 있게 되므로 테스트 처리 속도가 빨라집니다.
가급적이면 `setUp`에서 매번 객체를 생성하는 것을 지양하는 것이 좋습니다.

2021-07-26 02:03 UTC, lordmyshepherd commented on products/views.py
> +                        q_object &= Q(is_group=group)
위에 데코레이터에서 피드백 드린데로 뷰를 나누면 로직이 깔끔해지겠네요~

2021-07-26 02:03 UTC, lordmyshepherd commented on products/views.py
> +    @query_debugger
디버깅 데코레이터는 개발할때만 사용하셔야되고, 실제로 merge 및 배포하실때는 제거하셔야 합니다.
이유는 프린트 자체만으로도 실행 속도에 영향을 주기 때문입니다.

```suggestion
    @query_debugger
```

2021-07-26 02:03 UTC, lordmyshepherd commented on products/views.py
> +            user = User.objects.get(id=1)
데코레이터 붙여야되는거 아닌가요?

2021-07-26 15:14 UTC, Jacesoul commented on products/views.py
> +
네!

2021-07-26 15:15 UTC, Jacesoul commented on products/tests.py
> +class ProductsTest(TestCase):
setUpTestData()가 있었군요! 다시 한번 배웠습니다 :)

2021-07-26 15:16 UTC, Jacesoul commented on products/views.py
> +                        q_object &= Q(is_group=group)
말씀하신대로 폴더를 구분해서 뷰를 나눠봤습니다!

2021-07-26 15:17 UTC, Jacesoul commented on products/views.py
> +    @query_debugger
병민님이 공유해주신 @query_debugger 데코레이터 ORM최적화에 엄청난 도움이 되었습니다! 감사드려요~~

2021-07-26 15:17 UTC, Jacesoul commented on products/views.py
> +            user = User.objects.get(id=1)
뷰를 나눠서 데코레이터 붙였습니다!

2021-07-26 15:18 UTC, Jacesoul commented on core/views.py
> +                # request.user = User.objects.get(id=1)
폴더를 2개로 나누었는데 혹시 앤드포인트가 products/public, products/private으로 구분해도 될까요?

2021-07-27 01:36 UTC, lordmyshepherd commented on products/views.py
> +    @query_debugger
도움이 되었다니 너무너무 다행이에요 ㅎㅎ 저도 감사합니다!!!!

2021-07-27 02:06 UTC, lordmyshepherd requested changes
캐싱 부분만 제거해주시면 merge 하도록 하겠습니다!

2021-07-27 02:06 UTC, lordmyshepherd commented on products/views/private/views.py
> +            if category or subcategory or region or group:
```suggestion
```

2021-07-27 02:06 UTC, lordmyshepherd commented on products/views/private/views.py
> +                results = cache.get('user_products')
리스트를 반환하는 엔드포인트의 결과를 캐싱하는 것이 맞는지 고민 해보시면 좋을 것 같아요.
왜냐하면, 원래는 서버에 걸리는 부하 때문에 전체 리스트를 불러올 때, `offset`, `limit` 없이는 불러오지 못하도록 만들어야 합니다. 

아래와 같이 전체 값을 캐싱해놓고 반환하는 방법은 좋은 방법이 아닙니다!

```suggestion
```

2021-07-27 19:18 UTC, Jacesoul commented on products/views/private/views.py
> +                results = cache.get('user_products')
캐싱 부분만 제거후 다시 PR올렸습니다~!

2021-07-28 00:45 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-07-28 00:46 UTC, lordmyshepherd commented
고생 많으셨습니다!!

커밋이 8개네요!! 리베이스 부탁드려요~

2021-07-28 04:03 UTC, Jacesoul commented
커밋 하나로 리베이스하고 다시 PR올렸습니다~!

2021-07-28 04:56 UTC, lordmyshepherd commented
LGTM 👍

2021-07-28 04:56 UTC, merged