[ADD] 22기 안희수 호스트 등록기능
wecode-bootcamp-korea/22-2nd-iltal-backend pull request #5
Opened 2021-07-22 01:01 UTC by heesu-ahn

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
호스트 등록기능
		 
## 수정 사항들 자세한 내용
호스트 등록 기능
호스트 조회 기능

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-22 01:42 UTC, kst6294 reviewed
피드백 확인바랍니다!
오늘 진행되는 유닛테스트 진행후, 테스트코드와 함께 통신결과도 같이 올려주세요 :)

2021-07-22 01:42 UTC, kst6294 commented on users/views.py
> +                is_deleted  = is_deleted
```suggestion
                is_deleted  = False
```

2021-07-22 01:42 UTC, kst6294 commented on users/views.py
> +            is_deleted  = 0
```suggestion
```

2021-07-22 01:42 UTC, kst6294 commented on users/views.py
> +            hostuser    = json.loads(request.body)
```suggestion
            data   = json.loads(request.body)
```

2021-07-22 01:42 UTC, kst6294 commented on users/views.py
> +            if Host.objects.filter(user_id = user.id) :
```suggestion
            if Host.objects.filter(user_id = user.id).exists() :
```

2021-07-22 01:42 UTC, kst6294 commented on users/views.py
> +from users.models import User, Host
공백으로 구분해주세요.

2021-07-22 01:42 UTC, kst6294 commented on users/views.py
> +    def get(self, request, user_id):
user_id 는 데코레이터를 통해서 전달받을 수 있도록 해주세요!

2021-07-22 01:46 UTC, heesu-ahn commented on users/views.py
> +                is_deleted  = is_deleted
네

2021-07-22 01:46 UTC, heesu-ahn commented on users/views.py
> +            is_deleted  = 0
네

2021-07-22 01:46 UTC, heesu-ahn commented on users/views.py
> +            hostuser    = json.loads(request.body)
네

2021-07-22 01:46 UTC, heesu-ahn commented on users/views.py
> +            if Host.objects.filter(user_id = user.id) :
네

2021-07-22 01:47 UTC, heesu-ahn commented on users/views.py
> +from users.models import User, Host
네

2021-07-22 01:47 UTC, heesu-ahn commented on users/views.py
> +    def get(self, request, user_id):
아직 구현이 안되어 있어서 임시로 하였습니다.

2021-07-22 01:47 UTC, heesu-ahn commented
x-special/nautilus-clipboard
copy
file:///home/heesu/Pictures/Screenshot%20from%202021-07-22%2010-44-27.png

2021-07-22 02:13 UTC, lordmyshepherd requested changes

2021-07-22 02:13 UTC, lordmyshepherd commented on users/views.py
> +            hostuser = Host.objects.select_related('user').get(user_id = user_id)
여기서 `select_related`를 chaining해서 사용하시는 이유가 궁굼하네요~?

2021-07-22 04:09 UTC, heesu-ahn commented on users/views.py
> +            hostuser = Host.objects.select_related('user').get(user_id = user_id)
host 에 없는 user 테이블의 profile_url 을 가져와서 담기 위함인데
둘다 profile_url 을 가지고 있어서 사실 상 중복된 데이터라 고민입니다.

2021-07-22 09:29 UTC, heesu-ahn commented
![Screenshot from 2021-07-22 18-26-01](https://user-images.githubusercontent.com/77618489/126617887-fc46b1db-3869-470c-aecb-a834bcf88677.png)

2021-07-23 04:41 UTC, kst6294 requested changes
수정사항 확인바랍니다!

2021-07-23 04:41 UTC, kst6294 commented on users/views.py
> +            print(user_id)
불필요한 print 문은 제거해주세요!

2021-07-23 04:41 UTC, kst6294 commented on users/views.py
> +            profile_url = data['profile_url']
nickname, profile_url 등을 자주 사용하지 않기때문에 굳이 변수에 할당하지 않아도 괜찮을 것 같습니다.
굳이 변수에 할당하지 않으면 코드상 한 줄을 줄일 수 있을 것 같습니다.

```
profile_url = data['profile_rul']
```

2021-07-23 04:41 UTC, kst6294 commented on users/views.py
> +                host.save()
위의 피드백과 동일합니다.

2021-07-23 04:41 UTC, kst6294 commented on users/views.py
> +
공백 제거해주세요.

2021-07-23 04:41 UTC, kst6294 commented on users/views.py
> +    def get(self, request, user_id):
host 에 대한 세부 정보를 받는데, path parameter 로 전달받는 값이 host_id 가 아닌 user_id 인 것이 어색합니다.
host_id 를 받되, 실제로 인가된 사용자(호스트로 등록된)인지 검증해야할 것 같습니다.

그리고 인가된 사용자만 접근이 가능하도록 해주세요.

2021-07-23 04:41 UTC, kst6294 commented on users/views.py
> +    def post(self, request, user_id):
동일한 피드백입니다.

2021-07-23 04:41 UTC, kst6294 commented on users/views.py
> +                profile_url      = data['profile_url']
동일한 피드백입니다.

2021-07-23 04:41 UTC, kst6294 commented on users/views.py
> +                host.profile_url = profile_url
수정할 떄 nickname 과 profile_url 두 값을 반드시 입력받아야 하나요?

2021-07-23 04:49 UTC, heesu-ahn commented on users/views.py
> +            print(user_id)
네

2021-07-23 04:50 UTC, heesu-ahn commented on users/views.py
> +            profile_url = data['profile_url']
네

2021-07-23 04:52 UTC, heesu-ahn commented on users/views.py
> +                host.save()
네

2021-07-23 04:52 UTC, heesu-ahn commented on users/views.py
> +
네

2021-07-23 04:53 UTC, heesu-ahn commented on users/views.py
> +    def get(self, request, user_id):
지훈님 밸리데이터 머지 되면 이부분은 바로 변경될 사항입니다

2021-07-23 04:54 UTC, heesu-ahn commented on users/views.py
> +    def post(self, request, user_id):
네

2021-07-23 04:54 UTC, heesu-ahn commented on users/views.py
> +                profile_url      = data['profile_url']
네

2021-07-23 04:55 UTC, heesu-ahn commented on users/views.py
> +                host.profile_url = profile_url
둘 중 어느것을 받을지 몰라서 받는데 사실 프론트에서는 수정기능이 없고 등록기능만 있어
post 외에는 사용될 일이 없습니다

2021-07-23 05:00 UTC, heesu-ahn commented
커밋 메시지에 몇가지 질문 해주신 사항에 대한 사유 달아 놓았습니다
혹시 또 문의 사항 있으시면 코멘트 남겨 주세요

2021-07-23 06:44 UTC, lordmyshepherd requested changes
추가로 유닛 테스트 추가해주세요~

2021-07-23 06:44 UTC, lordmyshepherd commented on users/views.py
> +            hostuser = Host.objects.select_related('user').get(user_id = user_id)
희수님 아래 코드에보면 `host.user.id`가 아니라 `host.user_id`로 중간테이블에 있는 user_id를 불러오고 있기 때문에, host.profile_url을 사용하실거라면, select_related()는 필요 없는 코드가 될 것 같습니다.

2021-07-23 06:44 UTC, lordmyshepherd commented on users/views.py
> +            hostuser = Host.objects.select_related('user').get(user_id = user_id)
```suggestion
            host = Host.objects.select_related('user').get(user_id = user_id)
```

2021-07-23 06:45 UTC, lordmyshepherd commented
컨플릭트 해결해주세요~

2021-07-23 06:45 UTC, lordmyshepherd commented on users/views.py
> +    def get(self, request, user_id):
이부분은 완전히 구현되서, full로 제대로된 코드로 동작할 때 merge하도록 하겠습니다~

2021-07-23 07:12 UTC, heesu-ahn commented on users/views.py
> +            hostuser = Host.objects.select_related('user').get(user_id = user_id)
코드가 다른 브런치에서 작업하느라 혼선이 있었던 것 같습니다
select related 는 제외 되어 있었고 hostuser 는 지금 수정해서 반영했는데 다음 컨펌때 같이 올라갈 예정입니다

2021-07-25 09:44 UTC, heesu-ahn commented
![Screenshot from 2021-07-25 18-37-20](https://user-images.githubusercontent.com/77618489/126894821-c85000bf-afea-42d7-a77b-793b5eb070e4.png)

데코레이터 적용완료하였고 그 이전에 컨펌된 변수명 및 지적사항에 대해 수정되었습니다
테스트코드도 작성해서 정상적으로 구동되는 것을 확인하였습니다

2021-07-26 02:37 UTC, lordmyshepherd requested changes

2021-07-26 02:37 UTC, lordmyshepherd commented on users/views.py
> +                is_deleted  = False
`models.py`에서 이미 Host 모델의 `is_deleted`에 `default=False` 값을 가지고 있어서, 생성할 때, is_deleted에 값을 넣어줄 필요가 없을 것 같습니다~

```python
# models.py
class Host(TimeStampModel): 
    user        = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname    = models.CharField(max_length=200)
    profile_url = models.CharField(max_length=2000)
    is_deleted  = models.BooleanField(default=False)

    class Meta: 
        db_table = 'hosts'
```

```suggestion

```

2021-07-26 02:37 UTC, lordmyshepherd commented on users/views.py
> +            Host.objects.create(
if문 사이에 한줄 씩 띄워주시면 좋을 것 같아요~
그리고, `user = User.objects.get(id = request.user.id)`로 호출할 필요없이, filter()에서 한번만 조회하는게 더 효율적인 것 같네요~

```suggestion
            data = json.loads(request.body)
            
            if Host.objects.filter(user_id = request.user.id).exists() :
                return JsonResponse({"MESSAGE": "DUPLE_USER"}, status=404)
                
            Host.objects.create(
```

2021-07-26 02:37 UTC, lordmyshepherd commented on users/views.py
> +            return JsonResponse ({"MESSAGE":"SUCCESS"}, status = 201)
```suggestion
        try:
            data             = json.loads(request.body)
            host             = get_object_or_404(Host,user_id = request.user.id)
            host.nickname    = data['nickname']
            host.profile_url = data['profile_url']
            host.save()

        except AttributeError :
            return JsonResponse({'message': 'INVALID_USER'}, status=401) 

        except KeyError:
            return JsonResponse({'message': 'KEY_ERROR'}, status=401)

        except Host.DoesNotExist:
            return JsonResponse({'message': 'HOST_ERROR'}, status=401) 
                           
        return JsonResponse ({"MESSAGE":"SUCCESS"}, status = 201)   
```

2021-07-26 02:37 UTC, lordmyshepherd commented on users/views.py
> +            return JsonResponse ({"MESSAGE":"SUCCESS"}, status = 201)
인덴트 맞춰주시면 좋을 것 같아요~

2021-07-26 02:37 UTC, lordmyshepherd commented on users/tests.py
> +        client = Client(HTTP_USER_AGENT="Mozilla/5.0 ...", HTTP_Authorization = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxfQ.Rycaz6XldIy-q-xnORvTDQcdfOvEuTrE1BSSf74AiEQ")
token을 미리 생성한 후에 하드코딩해서 사용하는 방법인가요?
이렇게 되면, 서버에사 사용하고 있는 `SECRET_KEY` 또는 `ALGORITHM`이 변경될 경우 테스트코드도 영향을 받게 될 것 같습니다.

직접 로그인 엔드포인트를 호출해서 토큰을 받아온 이후에, host 등록 엔드포인트를 호출하는 방향으로 수정 부탁드립니다!
 

```suggestion
        client = Client(HTTP_USER_AGENT="Mozilla/5.0 ...", HTTP_Authorization = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxfQ.Rycaz6XldIy-q-xnORvTDQcdfOvEuTrE1BSSf74AiEQ")
```

2021-07-27 00:45 UTC, heesu-ahn commented
![Screenshot from 2021-07-26 20-36-19](https://user-images.githubusercontent.com/77618489/127077195-c92e74b5-e5b5-4999-8150-7a4a72f776da.png)
테스트 코드 수정 후 캡쳐하였습니다

2021-07-27 02:18 UTC, lordmyshepherd requested changes

2021-07-27 02:18 UTC, lordmyshepherd commented on core/views.py
> +def upload_data(file):
해당 PR에서 사용하지 않는 코드인 것 같네요??

2021-07-27 03:48 UTC, heesu-ahn commented on core/views.py
> +def upload_data(file):
profile_url 등록시 사용하는 코드입니다

2021-07-27 03:50 UTC, heesu-ahn commented on core/views.py
> +def upload_data(file):
profile_url = core.views.upload_data(request.FILES['profile_url'])

2021-07-28 01:25 UTC, lordmyshepherd requested changes

2021-07-28 01:25 UTC, lordmyshepherd commented on users/tests.py
> +    def test_hostview_post_success(self):
host 등록할 때, profile_image(`파일 데이터`)를 없이 테스트가 성공한건가요?

아래 view 코드를 보면, `request.FILES['profile_url']`에서 파일데이터를 받아와서 처리하고 있습니다.
테스트 코드도 실제로 파일데이터를 가지고 테스트를 해주셔야 합니다!

테스트가 제대로 동작하는 건가요?

```python
    @user_validator
    def post(self, request):
        try:
            aws = AWSAPI(AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, BUCKET)
            ..
            Host.objects.create(
                ..
                profile_url = aws.upload_file(request.FILES['profile_url'])
            )
```

2021-07-28 01:48 UTC, heesu-ahn commented
컨플릭트 해결하였습니다

2021-07-28 01:56 UTC, lordmyshepherd commented
LGTM 👍

2021-07-28 06:10 UTC, closed without merging