[iltal backend jihoon] 회원가입 및 user app 수정
wecode-bootcamp-korea/22-2nd-iltal-backend pull request #6
Opened 2021-07-22 02:01 UTC by wlgns410

- user signup
- UPDATE HOST class onotoone field
- UPDATE USER class
- commit user model

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-22 02:16 UTC, lordmyshepherd requested changes

2021-07-22 02:16 UTC, lordmyshepherd commented on users/views.py
> +        PASSWORD_REGES = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,16}$'
변수 선언과 try문 사이에 한칸 띄워주세요~

2021-07-22 02:16 UTC, lordmyshepherd commented on users/views.py
> +            return JsonResponse ({"MESSAGE":"SUCCESS"}, status = 201)
여기도 마찬가지 입니다~

2021-07-22 04:49 UTC, wlgns410 commented on users/views.py
> +        PASSWORD_REGES = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,16}$'
넵 수정했습니다

2021-07-22 04:49 UTC, wlgns410 commented on users/views.py
> +            return JsonResponse ({"MESSAGE":"SUCCESS"}, status = 201)
알겠습니다~

2021-07-22 07:53 UTC, wlgns410 commented
유닛테스트 적용한 뒤 푸쉬했습니다!

2021-07-23 01:11 UTC, wlgns410 commented
<img width="250" alt="스크린샷 2021-07-23 오전 10 10 53" src="https://user-images.githubusercontent.com/81137234/126727012-f742e68a-0612-486d-8d65-3ccacc7d1796.png">

2021-07-23 05:44 UTC, wlgns410 commented
modeling rebase 후 다시 푸쉬하였습니다.

2021-07-23 05:51 UTC, Kang-kyunghun commented
LGTM~!!

2021-07-23 05:51 UTC, merged